### PR TITLE
Rubocop

### PR DESCRIPTION
**Pull request by josephbridgwaterrowe**

### CODE REVIEW

**Comment by josephbridgwaterrowe** [comment]
@michaelachrisco please review.

**Comment by michaelachrisco** [comment]
I would suggest mentioning we rubocop all our pull requests as well.

**Comment by josephbridgwaterrowe** [comment]
Thanks, added.

**Comment by michaelachrisco** [comment]
Looks good. Rebase and I will merge.

**Comment by josephbridgwaterrowe** [comment]
I need to fix the author before merging.

**Comment by josephbridgwaterrowe** [comment]
@michaelachrisco all ready to merge.

**Pull request merged**
